baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Brewing Notes"
theme = 'PaperMod'

[params]
  disableSpecial1stPost = true
  images = ["/images/cover.jpg"]
  defaultTheme = "light" # dark, light

  
[params.homeInfoParams]
  Title = "Hi, I’m Deshana!"
  Content = "Notes, experiments, and write-ups on vision + ML. Coffee-fueled, book-approved."
  icon = "/apple-touch-icon.png"
  iconHeight = 35
  coverImage = "/images/test3.webp"   # ← add this
  coverAlt = "Brewing Notes cover"   # ← optional


[params.assets]
    # disableHLJS = true                # optional
    # disableFingerprinting = true      # optional
    favicon         = "images/favicon.ico"
    favicon16x16    = "images/favicon-16x16.png"
    favicon32x32    = "images/favicon-32x32.png"
    apple_touch_icon = "images/apple-touch-icon.png"
    safari_pinned_tab = "images/safari-pinned-tab.svg"
